---
version: "3"

services:
  ###
  # Scorpio Context Broker and deps
  ###
  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - kafka

  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.4
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check
    volumes:
      - redpanda_data:/var/lib/redpanda/data
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

  ###
  # Mobility dashboard
  ###
  mobility-dashboard:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ngsild-grafana-datasource
      GF_SECURITY_ADMIN_PASSWORD: odala2
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
    volumes:
      - grafana-data:/var/lib/grafana
      - ./ngsild-grafana-datasource/:/var/lib/grafana/plugins/ngsild-grafana-datasource:ro

volumes:
  pgdata:
  redpanda_data:
  grafana-data:
