---
version: "3.8"

services:
  ###
  # Scorpio Context Broker and deps
  ###
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-kafka-3.0.9
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - kafka

  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.4
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check
    volumes:
      - redpanda_data:/var/lib/redpanda/data
  postgres:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

  ###
  # Mobility dashboard
  ###
  mobility-dashboard:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      ## authentication
      GF_SECURITY_ADMIN_PASSWORD: odala2
      ## Install data source plugin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ngsild-grafana-datasource
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
      ## Configure datasource
      BROKER_URL: ${BROKER_URL:-http://scorpio:9090}
      # CONTEXT_URL: ${CONTEXT_URL:-http://host.docker.internal:3004/ngsi-context.jsonld}
      TIMESERIES_URL: ${TIMESERIES_URL:-http://scorpio:9090}
      GF_INSTALL_PLUGINS: https://github.com/zarelit/ngsild-grafana-datasource/releases/download/scorpio-support-rc1/ngsild-grafana-datasource.zip;ngsild-grafana-datasource
    volumes:
      # Persistent settings
      - grafana-data:/var/lib/grafana
      # Make datasource plugin available (helpful in development of the datasource)
      # - ./ngsild-grafana-datasource/:/var/lib/grafana/plugins/ngsild-grafana-datasource:ro
      # Provision the datasource declaratively
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
  ###
  # Data ingest
  ###
  otp-stops-extractor:
    image: nexus.phoops.it/phoops/otp-stops-extractor:v0.1.0
    environment:
      BROKER_URL: http://scorpio:9090
      OTP_URL: https://www.muoversintoscana.it/gw/otp/routers/toscana/index/graphql
      BOUNDING_BOX_MIN_LON: "11.801471"
      BOUNDING_BOX_MAX_LON: "11.922997"
      BOUNDING_BOX_MIN_LAT: "43.350637"
      BOUNDING_BOX_MAX_LAT: "43.503272"

volumes:
  pgdata:
  redpanda_data:
  grafana-data:
