version: "3"

services:
  ###
  # Main components
  ###
  quantumleap:
    image: orchestracities/quantumleap:${QL_VERSION:-latest}
    ports:
      - "8668:8668"
    depends_on:
      - scorpio
      - crate
      - redis
    environment:
      - CRATE_HOST=${CRATE_HOST:-crate}
      - USE_GEOCODING=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOGLEVEL=DEBUG

  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - kafka

  # ###
  # # QuantumLeap deps
  # ###
  crate:
    image: crate:${CRATE_VERSION:-4.6.7}
    command: crate
      -Cauth.host_based.enabled=false
      -Ccluster.name=democluster
      -Chttp.cors.enabled=true
      -Chttp.cors.allow-origin="*"
      -Cdiscovery.type=single-node
    environment:
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    volumes:
      - cratedata:/data

  redis:
    image: redis:${REDIS_VERSION:-6.2.3}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # ###
  # # Scorpio Context Broker Deps
  # ###
  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.4
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    ports:
      - 9092:9092
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ###
  # # smartcity-dashboard
  # ###
  ql-service:
    build:
      context: .
      dockerfile: ./backend/qlService/Dockerfile
    ports:
      - 8081:8081

  frontend-service:
    build:
      context: .
      dockerfile: ./backend/frontendService/Dockerfile
    ports:
      - 8080:8080

  frontend-app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000

  ###
  # smartcity-dashboard dependencies
  ###

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # smartcity-dashboard is not compatible with scorpio, yet
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
    healthcheck:
      test: curl --output /dev/null --silent --fail http://localhost:1026/v2

volumes:
  cratedata:
  redisdata:
  pgdata:
  redpanda_data:
