---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
data:
  GF_INSTALL_PLUGINS: "https://github.com/zarelit/ngsild-grafana-datasource/releases/download/scorpio-support-rc3/ngsild-grafana-datasource.zip;ngsild-grafana-datasource"
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ngsild-grafana-datasource
  BROKER_URL: http://scorpio-broker.odala.svc.cluster.local:9090
  TIMESERIES_URL: http://scorpio-broker.odala.svc.cluster.local:9090/ngsi-ld/v1/
