---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odala
resources:
  - deployment.yaml
  - service.yaml
  - config.yaml
  - datasource.yaml
  - dashboard.yaml
  - dashboard-provisioner.yaml
