---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odala

bases:
  - ../../base

resources:
  - secret.yaml

images:
  - name: grafana
    newName: grafana/grafana-oss
    newTag: 9.4.7
